services:
    - name: node-server
      env: node
      buildCommand: 'npm install'
      startCommand: 'npm start'
      plan: free
      branches:
          production:
              rootDir: .

    - name: python-whisper
      env: python
      buildCommand: |
          pip install -r requirements.txt
      startCommand: |
          python3 whisper_worker.py
      plan: free
      branches:
          production:
              rootDir: .
